// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// readsnpsc
Rcpp::List readsnpsc(Rcpp::StringVector& filename, arma::uvec& subjects, arma::uvec& snps, int nsub, arma::vec& snploc, arma::vec& snpbytes, arma::vec& blksnps, arma::vec& firstsnp, arma::vec& blkloc, arma::vec& blkbytes, Rcpp::LogicalVector& dosageonly);
RcppExport SEXP _readbinarydosage_readsnpsc(SEXP filenameSEXP, SEXP subjectsSEXP, SEXP snpsSEXP, SEXP nsubSEXP, SEXP snplocSEXP, SEXP snpbytesSEXP, SEXP blksnpsSEXP, SEXP firstsnpSEXP, SEXP blklocSEXP, SEXP blkbytesSEXP, SEXP dosageonlySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::StringVector& >::type filename(filenameSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type subjects(subjectsSEXP);
    Rcpp::traits::input_parameter< arma::uvec& >::type snps(snpsSEXP);
    Rcpp::traits::input_parameter< int >::type nsub(nsubSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type snploc(snplocSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type snpbytes(snpbytesSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type blksnps(blksnpsSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type firstsnp(firstsnpSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type blkloc(blklocSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type blkbytes(blkbytesSEXP);
    Rcpp::traits::input_parameter< Rcpp::LogicalVector& >::type dosageonly(dosageonlySEXP);
    rcpp_result_gen = Rcpp::wrap(readsnpsc(filename, subjects, snps, nsub, snploc, snpbytes, blksnps, firstsnp, blkloc, blkbytes, dosageonly));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_readbinarydosage_readsnpsc", (DL_FUNC) &_readbinarydosage_readsnpsc, 11},
    {NULL, NULL, 0}
};

RcppExport void R_init_readbinarydosage(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
