# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readsnpsc <- function(filename, subjects, snps, nsub, snploc, snpbytes, blksnps, firstsnp, blkloc, blkbytes, dosageonly) {
    .Call(`_readbinarydosage_readsnpsc`, filename, subjects, snps, nsub, snploc, snpbytes, blksnps, firstsnp, blkloc, blkbytes, dosageonly)
}

